### ISSUE TITLE
Bug Report 

### ISSUE THREAD

**Issue by headcase0570** [Athlon007/MOP#119]
**Describe the bug**
[A clear and concise description of what the bug is.]
Error notification on the main-menu console after launching the game.
**"ERROR: [MOP] Rule File CDPLAYER.mopconfig is for the newer version of MOP. Please update MOP right now!

Your MOP version: 3.8.0
Required version: 2.8.3"**

**To Reproduce**
[Steps to reproduce the behavior:
Start My Summer Car, patched with MSC Loader v1.2.6. After game start-up completes, the error will be displayed in the console log.

**Expected behavior**
[A clear and concise description of what you expected to happen.]
I expect the game to load without this error notification, because MOP is a never version than that which is required.

**Screenshots**
[If applicable, add screenshots to help explain your problem.]
![screenshot 209](https://user-images.githubusercontent.com/66142620/182217762-4ce8bf97-6e3a-4f3e-a29b-4505a6861181.png)

**Mod Report:**
[Go into mod settings and click "I FOUND A BUG", and paste the content here]
[MOP Bug Report - 2022-08-01_20-24.zip](https://github.com/Athlon007/MOP/files/9236372/MOP.Bug.Report.-.2022-08-01_20-24.zip)

**Additional context**
[Add any other context about the problem here.]
57 mods currently installed and functional.

**Comment by Athlon007** [comment]
Hi there,
You can temporarily overwrite that by editing CDPlayer.mopconfig yourself in any text editor.

Simply add “##” in front of min_ver line.

On 1 Aug 2022, at 21:25, headcase0570 ***@***.***> wrote:

﻿

Describe the bug
[A clear and concise description of what the bug is.]
Error notification on the main-menu console after launching the game.
**"ERROR: [MOP] Rule File CDPLAYER.mopconfig is for the newer version of MOP. Please update MOP right now!

Your MOP version: 3.8.0
Required version: 2.8.3"**

To Reproduce
[Steps to reproduce the behavior:
Start My Summer Car, patched with MSC Loader v1.2.6. After game start-up completes, the error will be displayed in the console log.

Expected behavior
[A clear and concise description of what you expected to happen.]
I expect the game to load without this error notification, because MOP is a never version than that which is required.

Screenshots
[If applicable, add screenshots to help explain your problem.]
[screenshot 209]<https://user-images.githubusercontent.com/66142620/182217762-4ce8bf97-6e3a-4f3e-a29b-4505a6861181.png>

Mod Report:
[Go into mod settings and click "I FOUND A BUG", and paste the content here]
MOP Bug Report - 2022-08-01_20-24.zip<https://github.com/Athlon007/MOP/files/9236372/MOP.Bug.Report.-.2022-08-01_20-24.zip>

Additional context
[Add any other context about the problem here.]
57 mods currently installed and functional.

**Comment by headcase0570** [comment]
`Hi there,
You can temporarily overwrite that by editing CDPlayer.mopconfig yourself in any text editor.

Simply add “##” in front of min_ver line.`

Thanks, that's gotten rid of the error!
