### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by KenyaDes** [Athlon007/MOP#68]
**Describe the bug**
i dont know what the bug is, MOP told me to send this .zip file

**To Reproduce**
[Steps to reproduce the behavior:
4. See error]
not sure because when I launch the game it just gives me instructions to send and generate the bug file

**Expected behavior**
my game works fine, idk it keeps telling me to send the bug file so I send it.

**Screenshots**
no screenshots, because it says in yellow text in the msc command prompt

**Game Version:**
the latest version (no experimental)

**Mod Report:**
[MOP Bug Report - 2022-05-04_11-37.zip](https://github.com/Athlon007/MOP/files/8617926/MOP.Bug.Report.-.2022-05-04_11-37.zip)

**Additional context**
unsure

**Comment by KenyaDes** [comment]
probably it's because of my mods I guess.

**Comment by Athlon007** [comment]
Hi there, the issue seems to be with MOP not being able to download the content of rule file server. Rule files are used to maintain compatibility with mods (ex. by making MOP ignore certain objects).

Here are some things that you could try to fix it:
- Check your firewall software if My Summer Car is allowed to send/receive information
- Check your router's DNS configuration

Alternatively, you can simply disable rule files checking by going into mod settings -> MOP Settings -> scroll down to "Rules" -> Uncheck "UPDATE RULES AUTOMATICALLY".

Then you can download the latest rule files pack from [THIS LINK](http://athlon.kkmr.pl/mop/).
